"""Generates BIM_Vision_Role7.ipynb (Colab). Run: python tools/build_notebook.py"""
import json, os

def md(*l): return {"cell_type": "markdown", "metadata": {}, "source": [x + "\n" for x in l]}
def code(*l): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": [x + "\n" for x in l]}

cells = [
  md("# BIM-Vision — Perception Pod, Role 7: Symbol/Object Detection",
     "Detect **door / window / stair / fixture** on floor plans with YOLOv11.",
     "",
     "**Deliverable:** per-class mAP@0.5 in MLflow + per-class calibrated thresholds.",
     "",
     "| Part | Needs GPU? | Time |",
     "|---|---|---|",
     "| 1 — push to GitHub | no | 2 min |",
     "| 2 — install deps | no | 3 min |",
     "| 3 — CPU smoke test + contract tests | no | 1 min |",
     "| 4 — ingest YOUR dataset | no | 1 min |",
     "| 5 — train | **YES** | 20–90 min |",
     "| 6 — evaluate + calibrate | **YES** | 5 min |",
     "| 7 — inference + handoff | **YES** | 1 min |",
     "",
     "> Run 1–4 first with no GPU. Only switch to GPU (Runtime → Change runtime type)",
     "> once PART 4 prints a sane class-balance table."),

  md("## PART 1 — Push code to GitHub",
     "Token is used only in this cell and never stored in the notebook."),
  code("import getpass, os, json, urllib.request, urllib.error",
       "GH_USER  = input('GitHub username: ').strip()",
       "GH_REPO  = input('Repo name [bim-vision-detection]: ').strip() or 'bim-vision-detection'",
       "GH_TOKEN = getpass.getpass('GitHub token (repo scope, hidden): ').strip()",
       "req = urllib.request.Request('https://api.github.com/user/repos',",
       "    data=json.dumps({'name': GH_REPO, 'private': True}).encode(),",
       "    headers={'Authorization': f'token {GH_TOKEN}', 'Accept': 'application/vnd.github+json'})",
       "try:",
       "    urllib.request.urlopen(req); print('repo created')",
       "except urllib.error.HTTPError as e:",
       "    print('create:', e.code, '(422 = already exists, fine)')"),
  code("from google.colab import files",
       "print('Upload bim-vision-detection.zip:')",
       "up = files.upload()",
       "os.system(f'rm -rf bim-vision-detection && unzip -q {next(iter(up))}')",
       "if os.path.isdir('bim-vision-detection'): os.chdir('bim-vision-detection')",
       "print('cwd:', os.getcwd()); print(sorted(os.listdir('.')))"),
  code("os.system('git init -q && git add -A && git -c user.email=ci@bim.local -c user.name=role7 commit -q -m \"Role 7 detection pipeline\"')",
       "remote = f'https://{GH_USER}:{GH_TOKEN}@github.com/{GH_USER}/{GH_REPO}.git'",
       "os.system('git branch -M main && git remote remove origin 2>/dev/null; git remote add origin ' + remote)",
       "print('push exit:', os.system('git push -u origin main'))",
       "print(f'-> https://github.com/{GH_USER}/{GH_REPO}')"),

  md("## PART 2 — Install dependencies"),
  code("!pip -q install pyyaml ultralytics mlflow",
       "import torch; print('CUDA available:', torch.cuda.is_available())",
       "!nvidia-smi || echo 'no GPU yet — fine for PARTS 3-4'"),

  md("## PART 3 — CPU smoke test + contract tests",
     "Proves the prep chain runs and the handoff matches the frozen",
     "`BuildingContext` schema field-for-field. Both must pass before training."),
  code("!python run_cpu_pipeline.py | tail -20",
       "print('=' * 60)",
       "!python tests/test_contract.py | tail -5"),

  md("## PART 4 — Ingest YOUR dataset (auto-detects the format)",
     "Handles **CubiCasa5k / COCO / YOLO / Pascal-VOC**. Works with the sample now",
     "and the Data & Annotation dataset later — same command, no code change.",
     "",
     "Read the *category → class resolution* block it prints. Anything listed as",
     "`keyword-guessed` should be confirmed and locked into `configs/base.yaml`.",
     "Anything `unmapped` is being ignored — make sure that's intentional."),
  code("from google.colab import files",
       "print('Upload your dataset zip (images + annotations):')",
       "d = files.upload()",
       "os.system(f'rm -rf dataset && mkdir dataset && unzip -q {next(iter(d))} -d dataset')",
       "print(sorted(os.listdir('dataset'))[:20])"),
  code("!python src/ingest.py --input dataset --images dataset --out yolo_dataset"),

  md("## PART 5 — Train  (GPU REQUIRED)",
     "Set `model.arch` in `configs/base.yaml` by dataset size and VRAM:",
     "`yolo11s` for a small sample, `yolo11m` default, `yolo11l` only with lots of both.",
     "For a first sample run, drop `train.epochs` to ~30 — you want a working",
     "pipeline and a baseline number, not a good model yet."),
  code("# optional: quick small-sample override without editing the file",
       "import yaml",
       "cfg = yaml.safe_load(open('configs/base.yaml'))",
       "cfg['model']['arch'] = 'yolo11s'; cfg['model']['pretrained'] = 'yolo11s.pt'",
       "cfg['train']['epochs'] = 30; cfg['train']['batch'] = 8",
       "yaml.safe_dump(cfg, open('configs/sample.yaml', 'w'), sort_keys=False)",
       "print('wrote configs/sample.yaml')"),
  code("!python src/train.py --config configs/sample.yaml --data yolo_dataset/data.yaml"),

  md("## PART 6 — Evaluate, calibrate, derive thresholds  (GPU)",
     "Produces the named deliverable (per-class mAP@0.5 in MLflow) plus",
     "`calibration.json` (Platt params + ECE before/after) and `thresholds.json`.",
     "Calibration runs BEFORE thresholding — thresholds picked on raw scores would",
     "be meaningless once inference calibrates."),
  code("!python src/evaluate.py --config configs/sample.yaml --data yolo_dataset/data.yaml \\",
       "  --weights runs/yolo-yolo11s/weights/best.pt --out eval_out",
       "import json",
       "print('thresholds:', json.load(open('eval_out/thresholds.json')))",
       "print('calibration:', json.load(open('eval_out/calibration.json')))"),

  md("## PART 7 — Inference → Context Engine handoff  (GPU)",
     "Always pass `--calibration`; without it `provenance.confidence` is the raw",
     "score, which violates the contract."),
  code("!python src/infer.py --weights runs/yolo-yolo11s/weights/best.pt \\",
       "  --thresholds eval_out/thresholds.json --calibration eval_out/calibration.json \\",
       "  --image PATH/TO/plan.png --out handoff.json",
       "import json; print(json.dumps(json.load(open('handoff.json')), indent=2)[:1500])"),

  md("## PART 8 — Save results back to GitHub",
     "Weights are gitignored by default (large). Push metrics + configs; store",
     "weights as a GitHub Release asset or in shared drive."),
  code("os.system('git add -A && git -c user.email=ci@bim.local -c user.name=role7 commit -q -m \"baseline: metrics, thresholds, calibration\" && git push')",
       "print('done')"),
]

nb = {"cells": cells,
      "metadata": {"kernelspec": {"display_name": "Python 3", "name": "python3"},
                   "language_info": {"name": "python"}, "accelerator": "GPU"},
      "nbformat": 4, "nbformat_minor": 5}
out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "notebooks", "BIM_Vision_Role7.ipynb")
os.makedirs(os.path.dirname(out), exist_ok=True)
json.dump(nb, open(out, "w"), indent=1)
print("wrote", out, "-", len(cells), "cells")
